kind: Service
apiVersion: v1
metadata:
  labels:
    app: alertmanager
  name: alertmanager
spec:
  type: NodePort
  selector:
    app: alertmanager
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 31001
    
