apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [smtp]
    enabled = true
    host = smtp.gmail.com:587
    skip_verify = true
    user = grafana@gmail.com
    password = 12345
    from_address = grafana@gmail.com
    from_name = Alert-graffana
    [emails]
    welcome_email_on_sign_up = true
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
kind: ConfigMap
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
